# Generated by Django 5.2.5 on 2025-09-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eletrobras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposito',
            name='banco_destino_nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Banco de Destino'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposito',
            name='nome_cliente_banco',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Nome do Cliente no Banco'),
            preserve_default=False,
        ),
    ]
