# Generated by Django 5.2.5 on 2025-09-11 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cigna_group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nivel',
            options={'ordering': ['numero'], 'verbose_name': 'Nível de Investimento', 'verbose_name_plural': 'Níveis de Investimento'},
        ),
        migrations.AddField(
            model_name='nivel',
            name='numero',
            field=models.IntegerField(default=0, unique=True, verbose_name='Número do Nível'),
            preserve_default=False,
        ),
    ]
